package dip.lab2;

import dip.lab2.api.ServiceQuality;
import dip.lab2.api.TipCalculator;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;

/**
 *
 * @author wsuetholz
 */
public class StartupGui extends javax.swing.JFrame {

//    private Map<String, Class<?>> tipChoices;
    private Map<String, TipCalculator> tipChoices;
    private TipCalculator tipCalc;
    private double tipAmount;

    /**
     * Creates new form StartupGui
     */
    public StartupGui() {
	tipAmount = 0.0;
	tipChoices = new HashMap<String, TipCalculator>();

	tipCalc = new BaggageServiceTipCalculator();
	tipChoices.put(BaggageServiceTipCalculator.class.getSimpleName(), tipCalc);
	tipChoices.put(FoodServiceTipCalculator.class.getSimpleName(), new FoodServiceTipCalculator());

	initComponents();
//	tipChoices = new HashMap<String, Class<?>>();
//
//	tipChoices.put(BaggageServiceTipCalculator.class.getSimpleName(), BaggageServiceTipCalculator.class);
//	tipChoices.put(FoodServiceTipCalculator.class.getSimpleName(), FoodServiceTipCalculator.class);

	jTipCalcChoices.setModel(new DefaultComboBoxModel<>(tipChoices.keySet().toArray()));
	jServiceQualityChoices.setModel(new DefaultComboBoxModel<>(ServiceQuality.values()));
	jLabel3.setText(tipCalc.getPromptString());
	jFormattedTextField1.setText(tipCalc.getCustomValueAsString());
	jTipAmount.setText(Double.toString(tipAmount));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTipCalcChoices = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jServiceQualityChoices = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jCalcTipButton = new javax.swing.JButton();
        jExitButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTipAmount = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTipCalcChoices.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jTipCalcChoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipCalcChoicesActionPerformed(evt);
            }
        });

        jLabel1.setText("Tip Calculator to Use:");

        jLabel2.setText("Quality of Service");

        jServiceQualityChoices.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jServiceQualityChoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jServiceQualityChoicesActionPerformed(evt);
            }
        });

        jLabel3.setText("jCustomValueLabel");

        jFormattedTextField1.setText("jFormattedTextField1");
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jCalcTipButton.setText("CalculateTip");
        jCalcTipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalcTipButtonActionPerformed(evt);
            }
        });

        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Tip Amount");

        jTipAmount.setText("jFormattedTextField2");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTipAmount, org.jdesktop.beansbinding.ELProperty.create("${value}"), jTipAmount, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jCalcTipButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jServiceQualityChoices, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTipCalcChoices, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jTipAmount))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTipCalcChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jServiceQualityChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTipAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCalcTipButton, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTipCalcChoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipCalcChoicesActionPerformed
	JComboBox cb = (JComboBox) evt.getSource();
	if (cb != null) {
	    String tipCalculatorName = (String) cb.getSelectedItem();
	    if (tipCalculatorName != null) {
		TipCalculator oldTipCalc = tipCalc;
		tipCalc = tipChoices.get(tipCalculatorName);
		if (tipCalc != null) {
		    this.jLabel3.setText(tipCalc.getPromptString());
		    this.jFormattedTextField1.setText(tipCalc.getCustomValueAsString());
		    tipAmount = tipCalc.calculateTip();
		    jTipAmount.setText(Double.toString(tipAmount));
		} else {
		    tipCalc = oldTipCalc;
		}
	    }
	}
    }//GEN-LAST:event_jTipCalcChoicesActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
	System.exit(0);
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jCalcTipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalcTipButtonActionPerformed
	String newValue = this.jFormattedTextField1.getText();
	if (newValue != null) {
	    tipCalc.setCustomValueFromString(newValue);
	}
	tipAmount = tipCalc.calculateTip();
	jTipAmount.setText(Double.toString(tipAmount));
    }//GEN-LAST:event_jCalcTipButtonActionPerformed

    private void jServiceQualityChoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jServiceQualityChoicesActionPerformed
	JComboBox cb = (JComboBox) evt.getSource();
	if (cb != null) {
	    ServiceQuality serviceQuality = (ServiceQuality) cb.getSelectedItem();
	    if (serviceQuality != null) {
		tipCalc.setServiceQuality(serviceQuality);
		tipAmount = tipCalc.calculateTip();
		jTipAmount.setText(Double.toString(tipAmount));
	    }
	}
    }//GEN-LAST:event_jServiceQualityChoicesActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
	// TODO add your handling code here:
	JFormattedTextField ftf = (JFormattedTextField) evt.getSource();
	if (ftf != null) {
	    String newValue = ftf.getSelectedText();
	    if (newValue != null) {
		tipCalc.setCustomValueFromString(newValue);
		tipAmount = tipCalc.calculateTip();
		jTipAmount.setText(Double.toString(tipAmount));
	    }
	}
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(StartupGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(StartupGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(StartupGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(StartupGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new StartupGui().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCalcTipButton;
    private javax.swing.JButton jExitButton;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jServiceQualityChoices;
    private javax.swing.JFormattedTextField jTipAmount;
    private javax.swing.JComboBox jTipCalcChoices;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
